### ISSUE TITLE
Responses inconsistent in documentation, test and production

### ISSUE THREAD

**Issue by Ram-Z** [starlingbank/starling-developer-sdk#23] opened 2018-12-02 13:15 UTC
For instance, `api/v1/transactions` is documented to respond with

```json
{
  "transactions": [
    {
      "id": "6f03a23a-bbfc-4479-8d4d-abb6a9119d27",
      "currency": "GBP",
      "amount": -23.45,
      "direction": "OUTBOUND",
      "created": "2017-07-05T18:27:02.335Z",
      "narrative": "Borough Barista",
      "source": "MASTER_CARD",
      "balance": 254.12
    }
  ]
}
```

But actually returns in production:
```json
{
  "_links": {
    "nextPage": {
      "href": "NOT_YET_IMPLEMENTED"
     }
  },
  "_embedded": {
    "transactions": [
      {
        "_links": {
          "detail": {
            "href": "...",
            "templated": false
          }
        },
        "id": "6f03a23a-bbfc-4479-8d4d-abb6a9119d27",
        "currency": "GBP",
        "amount": -23.45,
        "direction": "OUTBOUND",
        "created": "2017-07-05T18:27:02.335Z",
        "narrative": "Borough Barista",
        "source": "MASTER_CARD",
        "balance": 254.12
      }
    ]
  }
}
```

Tests are more similar to production but use "reference" instead of "narative".

I haven't looked at other responses yet, there may be other inconsistencies.

**Comment by domdomegg** [comment] 2019-12-12 14:09
Sorry for not addressing this earlier and for any confusion caused by poor documentation. Recently I've reviewed and improved a lot of the public API's documentation (I know it can still be better!) and more is auto-generated so should be consistent from the docs to the sandbox to production. The V1 APIs are now deprecated and the SDK no longer uses them, so I'm going to close this for now - but if you do spot any documentation inconsistencies or just ways it could be improved do shout in the Starling Developer Slack :)

**Closed by domdomegg** 2019-12-12 14:09 UTC
